server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: /api-docs

spring:
  jpa.hibernate:
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false

  flyway:
    locations: classpath:/config/db/migrations
