server:
  port: 3001

spring:
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_test?connectionCollation=utf8_general_ci&serverTimezone=UTC
    username: root
    password: root
