server:
  port: 3000

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo?connectionCollation=utf8_general_ci&serverTimezone=UTC
    username: root
    password: root
